qemu: remove --with-system-pixman from ./configure
Otherwise the build fails with:

    ERROR: unknown option --with-system-pixman

This patch is only needed because we use a custom QEMU that is ahead of
the Buildroot one, and will be removed when Buildroot updates QEMU
and notices that the option does not exist anymore like I did.